
project_id = "qifolopsdeeyrevbuxfl"

[auth]
enabled = true
external_url = "https://qifolopsdeeyrevbuxfl.supabase.co/auth/v1"
external_redirect_url = "https://id-preview--f3bdb396-b2bb-4755-9f8f-5bc2c9217c55.lovable.app/auth/callback"

[storage]
enabled = true
external_url = "https://qifolopsdeeyrevbuxfl.supabase.co/storage/v1"

[functions.generate-portfolio]
verify_jwt = false
